[package]
name = "rust_test"
version = "0.1.0"
authors = ["jin"]

[dependencies]
tokio = "0.1.7"
tokio-uds = "0.2.0"
tempdir = "0.3.7"
bytes = "0.4.8"
futures = "0.1.21"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bincode = "1.0.1"